---
- name: Verify that Virtualization Technology (VT) is enabled
  command: grep -c -E 'svm|vmx' /proc/cpuinfo
  changed_when: False
  failed_when: False
  register: result

- name: Notify if Virtualization Technology (VT) is disabled
  debug:
    msg: >
      Virtualization Technology (VT) is currently disabled. Please enable VT
      before running this role again.
  when:
    - not libvirt_host_require_vt | bool
    - result.rc != 0

- name: Fail if Virtualization Technology (VT) is disabled
  fail:
    msg: >
      Virtualization Technology (VT) is currently disabled. Please enable VT
      before running this role again.
  when:
    - libvirt_host_require_vt | bool
    - result.rc != 0
